# Generated by Django 5.2.6 on 2025-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(help_text="ФИО", max_length=70)),
                ("job_title", models.CharField(help_text="Должность", max_length=70)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
