# Generated by Django 5.2.6 on 2025-09-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_table", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeetable",
            options={"ordering": ["full_name"]},
        ),
        migrations.RemoveField(
            model_name="employeetable",
            name="owner",
        ),
        migrations.AlterField(
            model_name="employeetable",
            name="full_name",
            field=models.CharField(help_text="ФИО", max_length=70),
        ),
        migrations.AlterField(
            model_name="employeetable",
            name="job_title",
            field=models.CharField(help_text="Должность", max_length=70),
        ),
    ]
