# Generated by Django 5.2.6 on 2025-09-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee_table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="название таблицы", max_length=70)),
                ("term", models.IntegerField(blank=True, help_text="срок", null=True)),
                ("status", models.BooleanField(default=True, help_text="статус")),
                (
                    "work",
                    models.BooleanField(
                        default=True, help_text="взять в работу задачу"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="родительская задача",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_tasks",
                        to="task_table.tasktable",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        help_text="исполнитель",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_table",
                        to="employee_table.employeetable",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
