# Generated by Django 5.2.6 on 2025-09-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("link_to_parent_task", models.URLField()),
                ("performer", models.CharField(max_length=70)),
                ("term", models.IntegerField(max_length=5)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
