# Generated by Django 5.2.6 on 2025-09-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_table", "0003_alter_employeetable_options_and_more"),
        ("task_table", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasktable",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="tasktable",
            name="link_to_parent_task",
        ),
        migrations.RemoveField(
            model_name="tasktable",
            name="owner",
        ),
        migrations.AddField(
            model_name="tasktable",
            name="work",
            field=models.BooleanField(default=True, help_text="взять в работу задачу"),
        ),
        migrations.AlterField(
            model_name="tasktable",
            name="name",
            field=models.CharField(help_text="название таблицы", max_length=70),
        ),
        migrations.AlterField(
            model_name="tasktable",
            name="performer",
            field=models.ForeignKey(
                help_text="исполнитель",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_table",
                to="employee_table.employeetable",
            ),
        ),
        migrations.AlterField(
            model_name="tasktable",
            name="status",
            field=models.BooleanField(default=True, help_text="статус"),
        ),
        migrations.AlterField(
            model_name="tasktable",
            name="term",
            field=models.IntegerField(blank=True, help_text="срок", null=True),
        ),
        migrations.CreateModel(
            name="ParentTaskTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="название таблицы", max_length=70)),
                (
                    "performer",
                    models.ForeignKey(
                        help_text="исполнитель",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_table.employeetable",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tasktable",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="родительская задача",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_tasks",
                to="task_table.parenttasktable",
            ),
        ),
    ]
