# Generated by Django 5.2.6 on 2025-09-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_table", "0003_alter_employeetable_options_and_more"),
        ("task_table", "0003_alter_tasktable_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktable",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                help_text="исполнитель",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_table",
                to="employee_table.employeetable",
            ),
        ),
    ]
